language: python
python:
  - 3.6

env:
  - PIPENV_VENV_IN_PROJECT=1

install:
  - "pip install pipenv"
  - "pipenv install --dev"

script:
  - nosetests --with-coverage --cover-package=pyenigma

after_success:
  - coveralls
